/**:
  ros__parameters:
    task1_start_distance: 10.0  # Distance of the start line for Task 1
    task1_end_distance: 16.0    # Distance of the end line for Task 1+6m
    task3_start_distance: 30.0  # Distance of the start line for Task 3
    task3_end_distance: 150.0    # Distance of the end line for Task 3