/**:
  ros__parameters:
    task1_start_distance: 8.0  # Distance of the start line for Task 1
    task1_end_distance: 11.0    # Distance of the end line for Task 1+3m
    task3_start_distance: 28.8  # Distance of the start line for Task 3
    task3_end_distance: 170.0    # Distance of the end line for Task 3