/**:
  ros__parameters:
    system:
      type: diagnostic_aggregator/AnalyzerGroup
      path: system
      analyzers:
        debug_data_logger:
          type: diagnostic_aggregator/AnalyzerGroup
          path: debug_data_logger
          analyzers:
            storage_error:
              type: diagnostic_aggregator/GenericAnalyzer
              path: storage_error
              contains: ["bagpacker"]
              timeout: 3.0
