FROM ghcr.io/automotiveaichallenge/aichallenge2023-sim/autoware-universe-cuda:v1

RUN rm -rf /autoware/install/tier4_*_launch

ENV ROS_LOCALHOST_ONLY 0
ENV RMW_IMPLEMENTATION rmw_cyclonedds_cpp
ENV export RCUTILS_COLORIZED_OUTPUT 1
